services: docker

before_install:
  - docker build -t elmertest/xenial -f ci/Dockerfile-build .
  - docker ps -a

script:
  - docker run elmertest/xenial /bin/sh -c 'cmake -C ../opts-ubuntu-xenial.cmake ../elmerfem && make -j$(nproc) && ctest -L quick'

notifications:
  email: change
    
