services: docker
before_install:
- docker build -t elmertest/xenial -f ci/Dockerfile-build .
- docker ps -a
jobs:
  include:
    - stage: build
      script:
      - docker build -t elmerfem-build/xenial -f ci/Dockerfile-build-elmer .
    - stage: test
      script:
      - docker run elmerfem-build/xenial /bin/sh -c 'ctest -LE slow'
stage:
  - build
  - test
notifications:
  email: change
  flowdock:
    secure: "lu9jDOsW8lSOJr/d/7VGxU9nG1AAhc4kPKgfiOnLsBp2CJXVPAmbyaFMmaMfdJdHgM7pGW6fnoJSBtwyYfsB/GmXtmX9vKGwiKfAAGeUIGS15wzllHKjRQm3hDQ/MnO5wmj6r7dcSPjfLhy5ZFuiihoOSsBd9LpcMOetEsg99tA="
